# Generated by Django 4.2.9 on 2025-07-14 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Caja 2025'", max_length=100, unique=True, verbose_name='Nombre de la caja')),
                ('año', models.PositiveIntegerField(help_text='Año correspondiente a esta caja (ej. 2025)', verbose_name='Año')),
                ('activa', models.BooleanField(default=True, help_text='Marca si esta caja está actualmente en uso', verbose_name='¿Caja activa?')),
                ('saldo_caja', models.DecimalField(decimal_places=2, default=0, help_text='Saldo de la caja. Se actualiza automáticamente.', max_digits=10, verbose_name='Saldo de caja')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-año'],
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del concepto')),
                ('es_gasto', models.BooleanField(default=False, help_text='Marca si este concepto representa una salida de dinero', verbose_name='¿Es gasto?')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DenominacionEuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, unique=True, verbose_name='Valor en euros')),
                ('es_billete', models.BooleanField(default=False, help_text='Si es False, se considera moneda', verbose_name='¿Es billete?')),
                ('activa', models.BooleanField(default=True, help_text='Solo las denominaciones activas aparecerán en los formularios', verbose_name='¿Denominación activa?')),
            ],
            options={
                'verbose_name': 'Denominación Euro',
                'verbose_name_plural': 'Denominaciones Euro',
                'ordering': ['-valor'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Ejercicio 2025'", max_length=100, unique=True, verbose_name='Nombre del ejercicio')),
                ('año', models.PositiveIntegerField(help_text='Año correspondiente a este ejercicio (ej. 2025)', verbose_name='Año')),
                ('activo', models.BooleanField(default=True, help_text='Marca si este ejercicio está actualmente en uso', verbose_name='¿Ejercicio activo?')),
                ('saldo_banco', models.DecimalField(decimal_places=2, default=0, help_text='Saldo bancario propio del ejercicio, independiente de las cajas', max_digits=12, verbose_name='Saldo bancario del ejercicio')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del ejercicio', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['-año'],
            },
        ),
        migrations.CreateModel(
            name='HideShowFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModelFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('items_per_page', models.IntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del turno')),
                ('ejercicio', models.ForeignKey(help_text='Ejercicio al que pertenece este turno', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='dyn_dt.ejercicio', verbose_name='Ejercicio')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['ejercicio__nombre', 'nombre'],
                'unique_together': {('ejercicio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (€)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('justificante', models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº Justificante')),
                ('archivo_justificante', models.FileField(blank=True, help_text='Sube un PDF o imagen del justificante (opcional)', null=True, upload_to='justificantes/', verbose_name='Archivo justificante')),
                ('descripcion', models.TextField(help_text='Descripción detallada del movimiento', verbose_name='Descripción')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='dyn_dt.caja', verbose_name='Caja')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dyn_dt.concepto', verbose_name='Concepto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='dyn_dt.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (€)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('referencia_bancaria', models.CharField(blank=True, help_text='Número de referencia de la operación bancaria', max_length=50, null=True, verbose_name='Referencia bancaria')),
                ('archivo_justificante', models.FileField(blank=True, help_text='Sube un PDF o imagen del justificante (opcional)', null=True, upload_to='justificantes_banco/', verbose_name='Archivo justificante')),
                ('descripcion', models.TextField(help_text='Descripción detallada del movimiento bancario', verbose_name='Descripción')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dyn_dt.concepto', verbose_name='Concepto')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco', to='dyn_dt.ejercicio', verbose_name='Ejercicio')),
            ],
            options={
                'verbose_name': 'Movimiento de banco',
                'verbose_name_plural': 'Movimientos de banco',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='caja',
            name='ejercicio',
            field=models.ForeignKey(help_text='Ejercicio al que pertenece esta caja', on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='dyn_dt.ejercicio', verbose_name='Ejercicio'),
        ),
        migrations.CreateModel(
            name='MovimientoDinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entrada', models.PositiveIntegerField(default=0, help_text='Billetes/monedas que entran a la caja', verbose_name='Cantidad que entra')),
                ('cantidad_salida', models.PositiveIntegerField(default=0, help_text='Billetes/monedas que salen de la caja (cambio)', verbose_name='Cantidad que sale')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyn_dt.denominacioneuro', verbose_name='Denominación')),
                ('movimiento_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_dinero', to='dyn_dt.movimientocaja', verbose_name='Movimiento de Caja')),
            ],
            options={
                'verbose_name': 'Movimiento de Dinero',
                'verbose_name_plural': 'Movimientos de Dinero',
                'unique_together': {('movimiento_caja', 'denominacion')},
            },
        ),
        migrations.CreateModel(
            name='DesgloseCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad de unidades')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglose', to='dyn_dt.caja', verbose_name='Caja')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyn_dt.denominacioneuro', verbose_name='Denominación')),
            ],
            options={
                'verbose_name': 'Desglose de Caja',
                'verbose_name_plural': 'Desgloses de Caja',
                'ordering': ['-denominacion__valor'],
                'unique_together': {('caja', 'denominacion')},
            },
        ),
    ]
