# Generated by Django 4.2.9 on 2025-07-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del concepto')),
                ('es_gasto', models.BooleanField(default=False, help_text='Marca si este concepto representa una salida de dinero', verbose_name='¿Es gasto?')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Usa números positivos; se considera gasto o ingreso según el concepto', max_digits=10, verbose_name='Cantidad (€)')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha del movimiento')),
                ('justificante', models.CharField(blank=True, help_text='Número de justificante asociado (opcional)', max_length=5, null=True, verbose_name='Nº Justificante')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dyn_dt.concepto', verbose_name='Concepto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='dyn_dt.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
