# Generated by Django 4.2.9 on 2025-07-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campamento',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='campamento',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='modificado_por',
        ),
    ]
