# Generated by Django 4.2.9 on 2025-07-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0002_concepto_turno_movimientocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Caja 2025'", max_length=100, unique=True, verbose_name='Nombre de la caja')),
                ('año', models.PositiveIntegerField(help_text='Año correspondiente a esta caja (ej. 2025)', verbose_name='Año')),
                ('activa', models.BooleanField(default=True, help_text='Marca si esta caja está actualmente en uso', verbose_name='¿Caja activa?')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo actual')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-año'],
            },
        ),
        migrations.DeleteModel(
            name='MovimientoCaja',
        ),
    ]
