# Generated by Django 4.2.9 on 2025-07-29 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyn_dt', '0002_remove_campamento_modificado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campamento',
            name='modificado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en'),
        ),
        migrations.AddField(
            model_name='campamento',
            name='modificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='concepto',
            name='modificado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en'),
        ),
        migrations.AddField(
            model_name='concepto',
            name='modificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='modificado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='modificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='turno',
            name='modificado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en'),
        ),
        migrations.AddField(
            model_name='turno',
            name='modificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
    ]
