# Generated by Django 4.2.9 on 2025-07-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0002_movimientobanco_turno'),
        ('dyn_dt', '0003_populate_user_tracking'),
    ]

    operations = [
    ]
