# Generated by Django 4.2.9 on 2025-07-01 18:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0003_caja_delete_movimientocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (€)')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha del movimiento')),
                ('justificante', models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº Justificante')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='dyn_dt.caja', verbose_name='Caja')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dyn_dt.concepto', verbose_name='Concepto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='dyn_dt.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
