# Generated by Django 4.2.9 on 2025-07-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0004_movimientocaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solo se puede modificar al crear la caja. Después se actualiza automáticamente con los movimientos.', max_digits=10, verbose_name='Saldo inicial/actual'),
        ),
    ]
