# Generated by Django 4.2.9 on 2025-07-22 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyn_dt', '0004_merge_20250722_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora de creación del ejercicio', verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este ejercicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora de creación del ejercicio', verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concepto',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este ejercicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='denominacioneuro',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora de creación del ejercicio', verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='denominacioneuro',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este ejercicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='desglosecaja',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora de creación del ejercicio', verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desglosecaja',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este ejercicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora de creación del ejercicio', verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este ejercicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='movimientobanco',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora de creación del ejercicio', verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientobanco',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este ejercicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora de creación del ejercicio', verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este ejercicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='movimientodinero',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora de creación del ejercicio', verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientodinero',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este ejercicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora de creación del ejercicio', verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turno',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este ejercicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
