# Generated by Django 4.2.9 on 2025-07-24 10:02

import apps.dyn_dt.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyn_dt', '0005_alter_caja_creado_en_alter_caja_creado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoMovimientoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(help_text='Formato del movimiento bancario', max_length=100, verbose_name='Formato')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del formato', verbose_name='Creado en')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este formato', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Formato de Movimiento Bancario',
                'verbose_name_plural': 'Formatos de Movimiento Bancario',
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Asociación la Forja'", max_length=100, unique=True, verbose_name='Nombre de la cuenta')),
                ('titular', models.CharField(help_text='Nombre del titular de la cuenta', max_length=100, verbose_name='Titular')),
                ('IBAN', models.CharField(help_text='Número de cuenta IBAN', max_length=34, unique=True, verbose_name='IBAN')),
                ('activo', models.BooleanField(default=True, help_text='Marca si esta cuenta está actualmente en uso', verbose_name='¿Cuenta activa?')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la cuenta', verbose_name='Creado en')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó esta cuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['nombre'],
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
    ]
