# Generated by Django 4.2.9 on 2025-01-XX XX:XX

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0005_alter_caja_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento'),
        ),
    ]
