# Generated by Django 4.2.9 on 2025-07-24 10:08

import apps.dyn_dt.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyn_dt', '0006_formatomovimientobanco_cuentabancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del campamento')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del campamento', verbose_name='Creado en')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este campamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Campamento',
                'verbose_name_plural': 'Campamentos',
                'ordering': ['nombre'],
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
    ]
