# Generated by Django 4.2.9 on 2025-07-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0007_rename_observaciones_to_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='archivo_justificante',
            field=models.FileField(blank=True, help_text='Sube un PDF o imagen del justificante (opcional)', null=True, upload_to='justificantes/', verbose_name='Archivo justificante'),
        ),
    ]
