# Generated by Django 4.2.9 on 2025-07-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0007_campamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='ejercicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='dyn_dt.ejercicio', verbose_name='Ejercicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientobanco',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada del movimiento', verbose_name='Descripción'),
        ),
    ]
