# Generated by Django 4.2.9 on 2025-07-24 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyn_dt', '0008_movimientocaja_ejercicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='ejercicio',
        ),
        migrations.AlterField(
            model_name='caja',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la caja', verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó esta caja', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
