# Generated by Django 4.2.9 on 2025-07-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0009_alter_turno_options_turno_caja_alter_turno_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenominacionEuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, unique=True, verbose_name='Valor en euros')),
                ('es_billete', models.BooleanField(default=False, help_text='Si es False, se considera moneda', verbose_name='¿Es billete?')),
                ('activa', models.BooleanField(default=True, help_text='Solo las denominaciones activas aparecerán en los formularios', verbose_name='¿Denominación activa?')),
            ],
            options={
                'verbose_name': 'Denominación Euro',
                'verbose_name_plural': 'Denominaciones Euro',
                'ordering': ['-valor'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoDinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entrada', models.PositiveIntegerField(default=0, help_text='Billetes/monedas que entran a la caja', verbose_name='Cantidad que entra')),
                ('cantidad_salida', models.PositiveIntegerField(default=0, help_text='Billetes/monedas que salen de la caja (cambio)', verbose_name='Cantidad que sale')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyn_dt.denominacioneuro', verbose_name='Denominación')),
                ('movimiento_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_dinero', to='dyn_dt.movimientocaja', verbose_name='Movimiento de Caja')),
            ],
            options={
                'verbose_name': 'Movimiento de Dinero',
                'verbose_name_plural': 'Movimientos de Dinero',
                'unique_together': {('movimiento_caja', 'denominacion')},
            },
        ),
        migrations.CreateModel(
            name='DesgloseCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad de unidades')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglose', to='dyn_dt.caja', verbose_name='Caja')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyn_dt.denominacioneuro', verbose_name='Denominación')),
            ],
            options={
                'verbose_name': 'Desglose de Caja',
                'verbose_name_plural': 'Desgloses de Caja',
                'ordering': ['-denominacion__valor'],
                'unique_together': {('caja', 'denominacion')},
            },
        ),
    ]
