# Generated by Django 4.2.9 on 2025-07-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0009_remove_caja_ejercicio_alter_caja_creado_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-nombre'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.RemoveField(
            model_name='caja',
            name='año',
        ),
        migrations.AddField(
            model_name='caja',
            name='campamento',
            field=models.ForeignKey(default=1, help_text='Campamento al que pertenece esta caja', on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='dyn_dt.campamento', verbose_name='Campamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='nombre',
            field=models.CharField(help_text="Ej: 'Caja 1", max_length=100, unique=True, verbose_name='Nombre de la caja'),
        ),
    ]
