# Generated by Django 4.2.9 on 2025-07-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0010_alter_caja_options_remove_caja_año_caja_campamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='campamento',
            field=models.ForeignKey(default=1, help_text='Campamento al que pertenece este turno', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='dyn_dt.campamento', verbose_name='Campamento'),
            preserve_default=False,
        ),
    ]
