# Generated by Django 4.2.9 on 2025-07-07 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0010_denominacioneuro_movimientodinero_desglosecaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='saldo_banco',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo de los movimientos bancarios. Se actualiza automáticamente.', max_digits=10, verbose_name='Saldo bancario'),
        ),
        migrations.AddField(
            model_name='caja',
            name='saldo_caja',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo de los movimientos en efectivo. Se actualiza automáticamente.', max_digits=10, verbose_name='Saldo de caja (efectivo)'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma del saldo de caja y banco. Se calcula automáticamente.', max_digits=10, verbose_name='Saldo total'),
        ),
        migrations.CreateModel(
            name='MovimientoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (€)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('justificante', models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº Justificante')),
                ('archivo_justificante', models.FileField(blank=True, help_text='Sube un PDF o imagen del justificante (opcional)', null=True, upload_to='justificantes_banco/', verbose_name='Archivo justificante')),
                ('descripcion', models.TextField(help_text='Descripción detallada del movimiento bancario', verbose_name='Descripción')),
                ('referencia_bancaria', models.CharField(blank=True, help_text='Número de referencia de la operación bancaria', max_length=50, null=True, verbose_name='Referencia bancaria')),
                ('tipo_operacion', models.CharField(choices=[('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('domiciliacion', 'Domiciliación'), ('tarjeta', 'Pago con tarjeta'), ('bizum', 'Bizum'), ('otros', 'Otros')], default='transferencia', help_text='Tipo de operación bancaria', max_length=20, verbose_name='Tipo de operación')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco', to='dyn_dt.caja', verbose_name='Caja')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dyn_dt.concepto', verbose_name='Concepto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco', to='dyn_dt.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Movimiento de banco',
                'verbose_name_plural': 'Movimientos de banco',
                'ordering': ['-fecha'],
            },
        ),
    ]
