# Generated by Django 4.2.9 on 2025-07-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0011_turno_campamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobanco',
            name='campamento',
            field=models.ForeignKey(default=1, help_text='Campamento al que pertenece este movimiento bancario', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco', to='dyn_dt.campamento', verbose_name='Campamento'),
            preserve_default=False,
        ),
    ]
