# Generated by Django 4.2.9 on 2025-07-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0011_add_movimiento_banco_and_split_saldos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientobanco',
            name='tipo_operacion',
        ),
    ]
