# Generated by Django 4.2.9 on 2025-07-25 11:25

import apps.dyn_dt.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyn_dt', '0012_movimientobanco_campamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViaMovimientoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(help_text='Vía del movimiento bancario', max_length=100, verbose_name='Vía')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la vía de movimiento bancario', verbose_name='Creado en')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó esta vía de movimiento bancario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Vía de Movimiento Bancario',
                'verbose_name_plural': 'Vías de Movimiento Bancario',
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='FormatoMovimientoBanco',
        ),
    ]
