# Generated by Django 4.2.9 on 2025-07-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0012_remove_movimientobanco_tipo_operacion'),
        ('dyn_dt', '0012_remove_tipo_operacion_from_movimiento_banco'),
    ]

    operations = [
    ]
