# Generated by Django 4.2.9 on 2025-07-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0012_remove_tipo_operacion_from_movimiento_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Ejercicio 2025'", max_length=100, unique=True, verbose_name='Nombre del ejercicio')),
                ('año', models.PositiveIntegerField(help_text='Año correspondiente a este ejercicio (ej. 2025)', verbose_name='Año')),
                ('activo', models.BooleanField(default=True, help_text='Marca si este ejercicio está actualmente en uso', verbose_name='¿Ejercicio activo?')),
                ('saldo_banco', models.DecimalField(decimal_places=2, default=0, help_text='Saldo bancario propio del ejercicio, independiente de las cajas', max_digits=12, verbose_name='Saldo bancario del ejercicio')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del ejercicio', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['-año'],
            },
        ),
        migrations.AddField(
            model_name='caja',
            name='ejercicio',
            field=models.ForeignKey(blank=True, help_text='Ejercicio al que pertenece esta caja', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='dyn_dt.ejercicio', verbose_name='Ejercicio'),
        ),
    ]
