# Generated by Django 4.2.9 on 2025-07-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0013_viamovimientobanco_delete_formatomovimientobanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobanco',
            name='cuenta_bancaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco', to='dyn_dt.cuentabancaria', verbose_name='Cuenta bancaria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientobanco',
            name='via',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco', to='dyn_dt.viamovimientobanco', verbose_name='Vía de movimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viamovimientobanco',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la vía', verbose_name='Creado en'),
        ),
    ]
