# Generated by Django 4.2.9 on 2025-07-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0014_movimientobanco_cuenta_bancaria_movimientobanco_via_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viamovimientobanco',
            name='via',
        ),
        migrations.AddField(
            model_name='viamovimientobanco',
            name='nombre',
            field=models.CharField(default=1, help_text="Ej: 'Bizum', 'Transferencia', etc.", max_length=100, verbose_name='Nombre de la vía de movimiento bancario'),
            preserve_default=False,
        ),
    ]
