# Generated by Django 4.2.9 on 2025-07-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0015_fix_movimientobanco_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='ejercicio',
            field=models.ForeignKey(help_text='Ejercicio al que pertenece esta caja', on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='dyn_dt.ejercicio', verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldo_caja',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo de la caja. Se actualiza automáticamente.', max_digits=10, verbose_name='Saldo de caja'),
        ),
    ]
