# Generated by Django 4.2.9 on 2025-07-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dyn_dt', '0016_movimientocajaretiro_movimientocajadeposito'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movimientodinero',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='movimientodinero',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de movimiento de caja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientodinero',
            name='object_id',
            field=models.PositiveIntegerField(default=1, verbose_name='ID del objeto'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='movimientodinero',
            name='movimiento_caja',
        ),
    ]
