# Generated by Django 4.2.9 on 2025-07-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0016_alter_caja_ejercicio_alter_caja_saldo_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobanco',
            name='justificante',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº Justificante'),
        ),
        migrations.AddField(
            model_name='movimientobanco',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='Turno asociado al movimiento bancario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco', to='dyn_dt.turno', verbose_name='Turno'),
        ),
    ]
