# Generated by Django 4.2.9 on 2025-07-29 05:17

import apps.dyn_dt.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyn_dt', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('nombre', models.CharField(help_text="Ej: 'Caja 1", max_length=100, unique=True, verbose_name='Nombre de la caja')),
                ('activa', models.BooleanField(default=True, help_text='Marca si esta caja está actualmente en uso', verbose_name='¿Caja activa?')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('campamento', models.ForeignKey(help_text='Campamento al que pertenece esta caja', on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='dyn_dt.campamento', verbose_name='Campamento')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-nombre'],
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DenominacionEuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, unique=True, verbose_name='Valor en euros')),
                ('es_billete', models.BooleanField(default=False, help_text='Si es False, se considera moneda', verbose_name='¿Es billete?')),
                ('activa', models.BooleanField(default=True, help_text='Solo las denominaciones activas aparecerán en los formularios', verbose_name='¿Denominación activa?')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del ejercicio', verbose_name='Creado en')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este ejercicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Denominación Euro',
                'verbose_name_plural': 'Denominaciones Euro',
                'ordering': ['-valor'],
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimientoEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('cantidad_entrada', models.PositiveIntegerField(default=0, help_text='Billetes/monedas que entran a la caja', verbose_name='Cantidad que entra')),
                ('cantidad_salida', models.PositiveIntegerField(default=0, help_text='Billetes/monedas que salen de la caja (cambio)', verbose_name='Cantidad que sale')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_dinero', to='caja.caja', verbose_name='Caja')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de movimiento de caja')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.denominacioneuro', verbose_name='Denominación')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Movimiento de Efectivo',
                'verbose_name_plural': 'Movimientos de Efectivo',
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimientoCajaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe (€)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('descripcion', models.TextField(help_text='Descripción detallada del movimiento', verbose_name='Descripción')),
                ('caja_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_transferencia_destino', to='caja.caja', verbose_name='Caja de destino')),
                ('caja_origen', models.ForeignKey(help_text='Caja donde se registra el movimiento de transferencia', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_transferencia_origen', to='caja.caja', verbose_name='Caja de origen')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('ejercicio', models.ForeignKey(help_text='Ejercicio contable al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_transferencia', to='dyn_dt.ejercicio', verbose_name='Ejercicio')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('turno', models.ForeignKey(help_text='Turno al que pertenece este movimiento de transferencia', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_transferencia', to='dyn_dt.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Movimiento de Transferencia',
                'verbose_name_plural': 'Movimientos de Transferencia',
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimientoCajaRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe (€)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('descripcion', models.TextField(help_text='Descripción detallada del movimiento', verbose_name='Descripción')),
                ('retirado_por', models.CharField(help_text='Nombre de la persona que retira el efectivo', max_length=100, verbose_name='Retirado por')),
                ('caja', models.ForeignKey(help_text='Caja donde se registra el movimiento de retirada', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_retirada', to='caja.caja', verbose_name='Caja')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('ejercicio', models.ForeignKey(help_text='Ejercicio contable al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_retirada', to='dyn_dt.ejercicio', verbose_name='Ejercicio')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('turno', models.ForeignKey(help_text='Turno al que pertenece este movimiento de retirada', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_retirada', to='dyn_dt.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Movimiento de Retirada',
                'verbose_name_plural': 'Movimientos de Retirada',
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimientoCajaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe (€)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('descripcion', models.TextField(help_text='Descripción detallada del movimiento', verbose_name='Descripción')),
                ('archivo', models.FileField(blank=True, help_text='Archivo relacionado con el movimiento de ingreso', null=True, upload_to='movimientos_ingreso/', verbose_name='Archivo adjunto')),
                ('caja', models.ForeignKey(help_text='Caja donde se registra el movimiento de ingreso', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_ingreso', to='caja.caja', verbose_name='Caja')),
                ('concepto', models.ForeignKey(help_text="Concepto del movimiento de ingreso (ej. 'Inscripciones', 'Donación', etc.)", on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja_ingreso', to='dyn_dt.concepto', verbose_name='Concepto')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('ejercicio', models.ForeignKey(help_text='Ejercicio contable al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_ingreso', to='dyn_dt.ejercicio', verbose_name='Ejercicio')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('turno', models.ForeignKey(help_text='Turno al que pertenece este movimiento de ingreso', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_ingreso', to='dyn_dt.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Movimiento de Ingreso',
                'verbose_name_plural': 'Movimientos de Ingreso',
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimientoCajaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe (€)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('descripcion', models.TextField(help_text='Descripción detallada del movimiento', verbose_name='Descripción')),
                ('archivo', models.FileField(blank=True, help_text='Archivo relacionado con el movimiento de gasto', null=True, upload_to='movimientos_gasto/', verbose_name='Archivo adjunto')),
                ('caja', models.ForeignKey(help_text='Caja donde se registra el movimiento de gasto', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_gasto', to='caja.caja', verbose_name='Caja')),
                ('concepto', models.ForeignKey(help_text="Concepto del movimiento de gasto (ej. 'Compra de comida', 'Materiales', etc.)", on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja_gasto', to='dyn_dt.concepto', verbose_name='Concepto')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('ejercicio', models.ForeignKey(help_text='Ejercicio contable al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_gasto', to='dyn_dt.ejercicio', verbose_name='Ejercicio')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('turno', models.ForeignKey(help_text='Turno al que pertenece este movimiento de gasto', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_gasto', to='dyn_dt.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Movimiento de Gasto',
                'verbose_name_plural': 'Movimientos de Gasto',
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimientoCajaDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe (€)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('descripcion', models.TextField(help_text='Descripción detallada del movimiento', verbose_name='Descripción')),
                ('caja', models.ForeignKey(help_text='Caja donde se registra el movimiento de depósito', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_deposito', to='caja.caja', verbose_name='Caja')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('ejercicio', models.ForeignKey(help_text='Ejercicio contable al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_deposito', to='dyn_dt.ejercicio', verbose_name='Ejercicio')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('turno', models.ForeignKey(help_text='Turno al que pertenece este movimiento de depósito', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_deposito', to='dyn_dt.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Movimiento de Depósito',
                'verbose_name_plural': 'Movimientos de Depósito',
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DesgloseCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad de unidades')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del ejercicio', verbose_name='Creado en')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglose', to='caja.caja', verbose_name='Caja')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este ejercicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.denominacioneuro', verbose_name='Denominación')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Desglose de Caja',
                'verbose_name_plural': 'Desgloses de Caja',
                'ordering': ['-denominacion__valor'],
                'unique_together': {('caja', 'denominacion')},
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
    ]
