# Generated by Django 4.2.9 on 2025-07-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='denominacioneuro',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='denominacioneuro',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='desglosecaja',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='desglosecaja',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='movimientocajadeposito',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='movimientocajadeposito',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='movimientocajagasto',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='movimientocajagasto',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='movimientocajaingreso',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='movimientocajaingreso',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='movimientocajaretirada',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='movimientocajaretirada',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='movimientocajatransferencia',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='movimientocajatransferencia',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='movimientoefectivo',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='movimientoefectivo',
            name='modificado_por',
        ),
    ]
