# Generated by Django 4.2.9 on 2025-07-29 05:17

import apps.dyn_dt.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyn_dt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('nombre', models.CharField(help_text="Ej: 'Asociación la Forja'", max_length=100, unique=True, verbose_name='Nombre de la cuenta')),
                ('titular', models.CharField(help_text='Nombre del titular de la cuenta', max_length=100, verbose_name='Titular')),
                ('IBAN', models.CharField(help_text='Número de cuenta IBAN', max_length=34, unique=True, verbose_name='IBAN')),
                ('activo', models.BooleanField(default=True, help_text='Marca si esta cuenta está actualmente en uso', verbose_name='¿Cuenta activa?')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['nombre'],
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ViaMovimientoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('nombre', models.CharField(help_text="Ej: 'Bizum', 'Transferencia', etc.", max_length=100, verbose_name='Nombre de la vía de movimiento bancario')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Vía de Movimiento Bancario',
                'verbose_name_plural': 'Vías de Movimiento Bancario',
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimientoBancoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe (€)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('descripcion', models.TextField(help_text='Descripción detallada del movimiento', verbose_name='Descripción')),
                ('referencia_bancaria', models.CharField(blank=True, help_text='Número de referencia de la operación bancaria', max_length=50, null=True, verbose_name='Referencia bancaria')),
                ('archivo', models.FileField(blank=True, help_text='Archivo justificante del movimiento de ingreso', null=True, upload_to='movimientos_ingreso/', verbose_name='Archivo adjunto')),
                ('concepto', models.ForeignKey(help_text="Concepto del movimiento de ingreso (ej. 'Inscripciones', 'Donación', etc.)", on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_banco_ingreso', to='dyn_dt.concepto', verbose_name='Concepto')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco_ingreso', to='banco.cuentabancaria', verbose_name='Cuenta bancaria')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco_ingreso', to='dyn_dt.ejercicio', verbose_name='Ejercicio')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco_ingreso', to='dyn_dt.turno', verbose_name='Turno')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco_ingreso', to='banco.viamovimientobanco', verbose_name='Vía de movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento de Ingreso',
                'verbose_name_plural': 'Movimientos de Ingreso',
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimientoBancoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro', verbose_name='Modificado en')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe (€)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('descripcion', models.TextField(help_text='Descripción detallada del movimiento', verbose_name='Descripción')),
                ('referencia_bancaria', models.CharField(blank=True, help_text='Número de referencia de la operación bancaria', max_length=50, null=True, verbose_name='Referencia bancaria')),
                ('archivo', models.FileField(blank=True, help_text='Archivo de factura del movimiento de gasto', null=True, upload_to='movimientos_gasto/', verbose_name='Archivo adjunto')),
                ('concepto', models.ForeignKey(help_text="Concepto del movimiento de gasto (ej. 'Compra de comida', 'Materiales', etc.)", on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_banco_gasto', to='dyn_dt.concepto', verbose_name='Concepto')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco_gasto', to='banco.cuentabancaria', verbose_name='Cuenta Bancaria')),
                ('ejercicio', models.ForeignKey(help_text='Ejercicio al que pertenece este movimiento de gasto', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco_gasto', to='dyn_dt.ejercicio', verbose_name='Ejercicio')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('turno', models.ForeignKey(help_text='Turno al que pertenece este movimiento de gasto', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco_gasto', to='dyn_dt.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Movimiento de Gasto',
                'verbose_name_plural': 'Movimientos de Gasto',
            },
            bases=(apps.dyn_dt.mixins.UserTrackingMixin, models.Model),
        ),
    ]
