# Generated by Django 4.2.9 on 2025-07-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentabancaria',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='cuentabancaria',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='movimientobancogasto',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='movimientobancogasto',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='movimientobancoingreso',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='movimientobancoingreso',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='viamovimientobanco',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='viamovimientobanco',
            name='modificado_por',
        ),
    ]
