# Generated by Django 4.2.9 on 2025-07-29 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_dt', '0003_campamento_modificado_en_campamento_modificado_por_and_more'),
        ('banco', '0003_cuentabancaria_modificado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobancogasto',
            name='campamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco_gasto', to='dyn_dt.campamento', verbose_name='Campamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientobancoingreso',
            name='campamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco_ingreso', to='dyn_dt.campamento', verbose_name='Campamento'),
            preserve_default=False,
        ),
    ]
